GetStudent/Controllers/GetStudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetStudent.Controllers
{
    public class GetStudentController : Controller
    {
        public static ServiceReferenceGetStudent.Service1Client myService = new ServiceReferenceGetStudent.Service1Client();
        // GET: GetStudent
        public ActionResult Index()
        {            
            ViewBag.ListSinhVien = myService.Get_ListSinhVien();
            return View();
        }
        public ActionResult Create(string Name, string Email)
        {            
            ServiceReferenceGetStudent.SinhVien sinhvien = new ServiceReferenceGetStudent.SinhVien();
            if(!String.IsNullOrEmpty(Name) && !String.IsNullOrEmpty(Email))
            {
                sinhvien.Name = Name;
                sinhvien.Email = Email;
                myService.Insert_ListSinhVien(sinhvien);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

GetStudent/Views/GetStudent/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "GetStudent", FormMethod.Post))
{
    <p>
        Name: @Html.TextBox("Name")
        Email: @Html.TextBox("Email")
    </p><br />
    <input type="submit" value="Create" class="btn btn-default" />

}

GetStudent/Views/GetStudent/Index.cshtml
@{
    ViewBag.Title = "Index";
    
}

<h2>Index</h2>
<button onclick="location.href='@Url.Action("Create", "GetStudent")';">Create New</button>
<br />
<table class="steelBlueCols">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Email
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in ViewBag.ListSinhVien)
        {
            <tr>
                <td>@s.Id</td>
                <td>@s.Name</td>
                <td>@s.Email</td>
                <td></td>
            </tr>
        }
    </tbody>
</table>
<style>
    table.steelBlueCols {
  border: 4px solid #555555;
  background-color: #555555;
  width: 400px;
  text-align: center;
  border-collapse: collapse;
}
table.steelBlueCols td, table.steelBlueCols th {
  border: 1px solid #555555;
  padding: 5px 10px;
}
table.steelBlueCols tbody td {
  font-size: 12px;
  font-weight: bold;
  color: #FFFFFF;
}
table.steelBlueCols td:nth-child(even) {
  background: #398AA4;
}
table.steelBlueCols thead {
  background: #398AA4;
  border-bottom: 10px solid #398AA4;
}
table.steelBlueCols thead th {
  font-size: 15px;
  font-weight: bold;
  color: #FFFFFF;
  text-align: left;
  border-left: 2px solid #398AA4;
}
table.steelBlueCols thead th:first-child {
  border-left: none;
}

table.steelBlueCols tfoot td {
  font-size: 13px;
}
table.steelBlueCols tfoot .links {
  text-align: right;
}
table.steelBlueCols tfoot .links a{
  display: inline-block;
  background: #FFFFFF;
  color: #398AA4;
  padding: 2px 8px;
  border-radius: 5px;
}

</style>